### ISSUE TITLE
 Error: certificate has expired

### ISSUE THREAD

**Issue by dovancao** [ttezel/twit#474] opened 2018-10-29 07:55 UTC
HI everyone, I'm new on nodejs
When I try to use Twit. I got this, I have no idea about how to fix it. Thank you for your help
This is my code
```
const config = require('../config');
var Twit = require('twit');

var client = new Twit({
  consumer_key: config.customerKey,
  consumer_secret: config.customerSecret,
  access_token: config.accessTokenApi,
  access_token_secret: config.accessTokenSecret,
  timeout_ms: 60*1000,
  strictSSL: true,
});

tweetIt();

function tweetIt() {

  var r = Math.floor(Math.random()*100);

  tweet = {
    status: 'here is random number ' + r + '#coding it'
  }

  client.post('statuses/update', tweet, tweeted);

  function tweeted(err, data, response) {
    if (err) {
      console.log('Something went wrong! ');
      console.log(err)
    } else {
      console.log('It worked')
    }
  }
}
```

Error: 
```
{ Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8) code: null, statusCode: null, allErrors: [], twitterReply: ''
```

**Comment by larvata** [comment] 2018-10-29 09:58
Do you access twitter via proxy?
I think you can add following code at the top of your snippet to workaround.
Turn off this flag will make your connection insecure, google it before setting this flag.

```javascript
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
```

**Comment by dovancao** [comment] 2018-10-29 13:26
How can I access twitter via proxy by nodejs?

**Comment by larvata** [comment] 2018-10-29 13:45
@dovancao No, you don't need to do this.
I mean this error often caused by a proxy.

I have no idea to resolve this issue.

ps. 
Can you access twitter without any error?
Is your local time correct? its related with certificate validation.

**Comment by dovancao** [comment] 2018-10-29 13:49
When I setting flag like this
```
 function tweetIt() {
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

  var r = Math.floor(Math.random()*100);

  tweet = {
    status: 'here is random number ' + r + '#coding_it'
  }

  client.post('statuses/update', tweet, tweeted);

  function tweeted(err, data, response) {
    if (err) {
      console.log('Something went wrong! ');
      console.log(err)
    } else {
      console.log('It worked')
    }
  }
}
```

I got new error:
```
  Unexpected reply from Twitter upon obtaining bearer token
```

**Comment by dovancao** [comment] 2018-10-29 13:51
Yes, I access it via VPN -Windscribe. And then I got that problem

**Comment by larvata** [comment] 2018-10-29 14:08
I think you can set the `strictSSL = false` to workaround this issue.
Please notice turn off strictSSL and NODE_TLS_REJECT_UNAUTHORIZED can make your connection insecure.

**Comment by dovancao** [comment] 2018-10-29 15:48
@larvata If I did like that, I got new issue 
```
 Unexpected reply from Twitter upon obtaining bearer token
```

**Comment by dovancao** [comment] 2018-10-29 15:49
How can I fix it? Do I need to request a new Twitter account?

**Comment by larvata** [comment] 2018-10-29 17:26
I can successfully post a tweet by using your code(with NODE_TLS_REJECT_UNAUTHORIZED='0' and strictSSL = false) behind a proxy.
I don't know why it is failed at your side.

**Comment by dovancao** [comment] 2018-10-30 06:32
It is so strange @@. Thank you for your help. I will try another laptop.

**Comment by maziyarpanahi** [comment] 2018-11-04 10:49
If the solution works please remember to close the issue. Thanks @dovancao

**Closed as completed** 2018-11-15 08:52 UTC
