### ISSUE TITLE
TypeError in tweet node module

### ISSUE THREAD

**Issue by tanoybhowmick** [ttezel/twit#210] opened 2015-10-03 07:57 UTC
I am using latest node js and express 3.x.x. When I built the with twit module it throws an error like "TypeError :  Cannot read property 'on' of undefined at.."  at the node_modules/twit/lib/streaming-api-connection.js:70.
![2015-10-03_1323](https://cloud.githubusercontent.com/assets/14951058/10261983/6494ef3a-69d2-11e5-851a-a0f1a8b5f916.png)

**Comment by dsalcedo** [comment] 2015-10-12 20:48
can you share your code?

**Comment by ttezel** [comment] 2016-01-30 23:30
Closing this as I can't reproduce it, feel free to reopen if you have code that reproduces this! Thanks :)

**Closed by ttezel** 2016-01-30 23:30 UTC
