### ISSUE TITLE
I am trying to make a follow bot, but I run into this. 

### ISSUE THREAD

**Issue by Daniel-Stahl** [ttezel/twit#237] opened 2016-02-01 21:58 UTC
The follow bot is starting
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Gzip error: incorrect header check
    at Object.exports.makeTwitError (/Users/Ortega2/Desktop/twitterbot/node2/node_modules/twit/lib/helpers.js:74:13)
    at Gunzip.<anonymous> (/Users/Ortega2/Desktop/twitterbot/node2/node_modules/twit/lib/streaming-api-connection.js:112:31)
    at emitOne (events.js:95:20)
    at Gunzip.emit (events.js:182:7)
    at Zlib._handle.onerror (zlib.js:366:10)

Here is my code:
`console.log('The follow bot is starting');

var Twit = require('twit');

var config = require('./config');
var T = new Twit(config);

// Setting up a user stream
var stream = T.stream('user');

// Anytime someone follows me
stream.on('follow', followed);

function followed(eventMsg) {
  console.log("Follow event!");
  var name = eventMsg.source.name;
  var screenName = eventMsg.source.screen_name;
  tweetIt('.@' + screenName + ' do you like rainbows?');
}

function tweetIt(txt) {

	var tweet = {
	  status: txt
	}

	T.post('statuses/update', tweet, tweeted);

	function tweeted(err, data, response) {
	  if (err) {
	  	console.log("Something went wrong!");
	  } else {
	    console.log("It worked!");
	  }
	}
}`

**Comment by ttezel** [comment] 2016-02-01 22:03
What version of `twit` are you using? And what version of `node` are you using?

**Comment by ttezel** [comment] 2016-02-01 22:10
Just tested your code with the latest version of twit and node v0.10.0 and node v0.12.0, works without issues.

**Comment by jedi4ever** [comment] 2016-02-01 23:01
just hitting the same issue now . v0.12 , twit v 2.1.1

**Comment by ttezel** [comment] 2016-02-01 23:13
@jedi4ever I can't reproduce the issue, can you please show code that reproduces the issue?

**Comment by jedi4ever** [comment] 2016-02-01 23:16
code is pretty standard:


```
 debug("starting twitter tracker")
 T = new Twit @config.twitter.keys

 stream = T.stream 'statuses/filter',
   track: @config.url.short

 stream.on 'connect', (request) ->
   console.log "[twitter:connect] #{request.uri.href}"

 stream.on 'connected', (response) ->
   console.log "[twitter:connected] #{response.request.uri.href}"

 stream.on 'disconnect', (disconnectMessage) ->
   console.log "[twitter:disconnect] #{disconnectMessage}"

 stream.on 'reconnect', (request, response, connectInterval) ->
   console.log "[twitter:reconnect] #{request.uri.href} (retry in #{connectInterval}ms)"

 stream.on 'warning', (warning) ->
   console.log "[twitter:warning] #{warning}"

 stream.on 'error', (error) ->
   console.log "[twitter:error] #{error}"

 stream.on 'tweet', (tweet) =>
   console.log "[twitter:tweet] #{tweet.id_str} by @#{tweet.user.screen_name} (##{tweet.user.id_str})"

```

**Comment by jedi4ever** [comment] 2016-02-01 23:17
I'm trying to see if I have the same issues going back to 2.1.1

**Comment by ttezel** [comment] 2016-02-01 23:21
@jedi4ever where are you calling `.stop()` on the stream? I thought the issue was that you were calling `.stop()` on the stream and seeing that it was reconnecting.

**Comment by jedi4ever** [comment] 2016-02-01 23:25
no - I'm not calling stop during the operation ; it's running as a daemon.
kinda lost the terminal log...  but from what I recall:

- it was backing off and retrying
- then hitting connect & connected 
- then start telling me on the gzip error

rolling back to 2.1.1 makes thing working again

**Comment by jedi4ever** [comment] 2016-02-01 23:26
It's kinda late , past midnight ; and need to launch - will report back when I have more info

**Comment by ttezel** [comment] 2016-02-01 23:38
Okay it looks like this is occurring because I turned gzip on starting with twit v2.1.1. If twitter sends back an uncompressed HTTP response body this can occur. I have fixed this by emitting `parser-error` instead of `error` event if this happens. This should be fixed in twit v2.2.2.

**Comment by ttezel** [comment] 2016-02-01 23:46
@jedi4ever @Daniel-Stahl could you let me know if you still encounter that issue with twit v2.2.2? Thanks!!!

**Comment by Daniel-Stahl** [comment] 2016-02-02 00:03
@ttezel thanks for responding so quickly. I have latest node.js 5.5.0 and How do I check Twit? I think I have before 2.2.2

**Comment by ttezel** [comment] 2016-02-02 00:06
"Npm update twit" downloads and installs the latest version



—

**Comment by Daniel-Stahl** [comment] 2016-02-02 00:13
@ttezel awesome im not getting errors, but my bot isnt executing the status txt.

**Comment by ttezel** [comment] 2016-02-02 00:33
@Daniel-Stahl what error are you getting? Make sure to double check that you're not trying to tweet a status that you just tweeted, as Twitter will block you from reposting the same tweet.

**Comment by Daniel-Stahl** [comment] 2016-02-02 00:36
@ttezel im not getting errors now, but when I follow the bot Im suppose to get a tweet with a thank you. Its not executing. Is it node?

**Comment by Daniel-Stahl** [comment] 2016-02-02 00:52
Okay im making progress. Apparently when my bot follows someone it executes the code. I want the other way around.

**Comment by Daniel-Stahl** [comment] 2016-02-02 18:12
@ttezel I got it working now thanks for the fix.

**Comment by ttezel** [comment] 2016-02-02 22:27
@Daniel-Stahl awesome :) Closing.

**Closed by ttezel** 2016-02-02 22:27 UTC
