### ISSUE TITLE
Infinite reconnection loop when Gzip parse error

### ISSUE THREAD

**Issue by super-ienien** [ttezel/twit#245] opened 2016-02-25 23:59 UTC
Hi,

I don't understand why the stream is not stopped when there is a gzip parse error. This is causing the stream reconnect infinitly. And there is no 'error' event emitted as well. Instead it is a not documented event : 'parser-error'

Reproduce this issue : connect to user stream api, shutdown your internet connection, wait one minute, restart your internet connection, wait for the stream to reconnect, it will never reconnect because you will get a 401 "need authentication" status code. The Gzip parser will throw an error.

Fix : close the stream and emit an 'error' event

**Comment by mcorb** [comment] 2016-03-03 17:24
@super-ienien Does #242 fix the issue you describe? Perhaps you could comment there to help get the fix reviewed?

**Comment by alchen** [comment] 2016-03-03 19:10
@mcorb The authentication error, in my case, seems to be caused by the oauth timestamp added by Twit, and it is not fixed by #242. I'm uncertain whether my hack of simply removing it is the proper fix so I didn't produce a pull request for that.

**Comment by super-ienien** [comment] 2016-03-23 00:22
@alchen You're right about the oauth timestamp. I made a quick fix to update the timestamp at each reconnection attempt and it does not run into an infinite reconnection loop. Thanks

**Comment by ttezel** [comment] 2016-05-02 03:15
hey guys the timestamp issue has been fixed in twit v2.2.4. `run npm updat twit` to get it, and let me know if you see this again! Thanks :D

**Closed by ttezel** 2016-05-02 03:15 UTC
